api_key: <API_KEY>
email: <EMAIL_ADDR>
zone_id: <ZONE_ID>
account_id: <ACCOUNT_ID>
scope: <zone|account>
dbpath: /var/lib/crowdsec/data/crowdsec.db
piddir: /var/run/
update_frequency: 30s
daemonize: true
log_mode: file
log_dir: /var/log/